# Generated by Django 3.0.8 on 2020-08-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200807_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='photo',
            new_name='image',
        ),
    ]
